name: Storage Account Creation
on: 
 workflow_dispatch:
jobs:
  storageFor-Dev:

   runs-on: ubuntu-latest
   environment: Development
   steps:
     - name: Checkout source code 
       uses: actions/checkout@master
   
     - uses: azure/login@v1
       with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
     - name: Deploy ARM Template
       uses: azure/arm-deploy@v1
       with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./ARMTemplate_blobStorage/blobstorageA.json
          parameters: ./ARMTemplate_blobStorage/blobstorage_parameters-dev.json
  storageFor-Prod:
    runs-on: ubuntu-latest
    needs: storageFor-Dev
    environment: Production
    steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
                  
        - name: Checkout source code 
          uses: actions/checkout@v2
               
        - name: Deploy ARM Template
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: ${{ secrets.AZURE_RG }}
            template: ./ARMTemplate_blobStorage/blobstorageA.json
            parameters: ./ARMTemplate_blobStorage/blobstorage_parameters-prod.json
