name: LA-Build&Deploy-Dev
on: push
jobs:
  LA-BiludAndDeploy-Dev:
   runs-on: ubuntu-latest
   environment: Development
   steps:
     - name: Checkout source code 
       uses: actions/checkout@master
   
     - uses: azure/login@v1
       with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
     - name: Deploy ARM Template
       uses: azure/arm-deploy@v1
       with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Templates/RssConnection.json
          parameters: ./Templates/Dev-Parameters.json
  LA-BiludAndDeploy-prod:
    runs-on: ubuntu-latest
    needs: LA-BiludAndDeploy-Dev
    environment: Production
    steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
                  
        - name: Checkout source code 
          uses: actions/checkout@v2
               
        - name: Deploy ARM Template
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: ${{ secrets.AZURE_RG }}
            template: ./Templates/RssConnection.json
            parameters: ./Templates/Prod-Pramaters.json
