name: Sharepoint
on: 
 workflow_dispatch:
 push:
   branches-ignore:
     - 'Sharepoint'
jobs:
  Sharepoint-Dev:

   runs-on: ubuntu-latest
   environment: Development
   steps:
     - name: Checkout source code 
       uses: actions/checkout@master
   
     - uses: azure/login@v1
       with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
     - name: Deploy Sharepoint Template
       uses: azure/arm-deploy@v1
       with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./ARMtemplate_sharepoint/sharepoint_deployment_template.json
          parameters: ./ARMtemplate_sharepoint/sharepoint_deployment_parameters.json
        